[theme]
primaryColor = "#0056b3"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#111827"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[ui]
hideTopBar = true